name: Blank workflow
on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push to daki.cc
        uses: wangyucode/sftp-upload-action@v1.4.6
        with:
          host: ${{ secrets.SFTP_ADDRESS }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          localDir: .
          remoteDir: /
          dryRun: false
